"use client";
import Link from "next/link";
import { FormEvent, useMemo, useState } from "react";
import { Navigation } from "../components/Navigation";
import { portfolio as seed, stocks } from "../data";
type Position = (typeof seed)[number];
const fx = 1409.94;

export function PortfolioView() {
  const [positions,setPositions] = useState<Position[]>(seed);
  const totals = useMemo(() => positions.reduce((acc,p) => { const rate=p.currency==="USD"?fx:1; acc.value+=p.qty*p.price*rate; acc.cost+=p.qty*p.avg*rate; return acc; },{value:0,cost:0}),[positions]);
  const pnl=totals.value-totals.cost;
  function addPosition(event:FormEvent<HTMLFormElement>) { event.preventDefault(); const data=new FormData(event.currentTarget); const stock=stocks.find((item)=>item.symbol===data.get("symbol")); if(!stock)return; const qty=Number(data.get("qty")); const avg=Number(data.get("avg")); setPositions((current)=>[...current.filter((p)=>p.symbol!==stock.symbol),{symbol:stock.symbol,name:stock.name,qty,avg,price:stock.price,currency:stock.currency}]); event.currentTarget.reset(); }
  return <div className="app-shell"><Navigation/><main className="main-area"><header className="topbar"><div className="mobile-brand"><span className="brand-mark">S</span><strong>signalist</strong></div><div className="live-pill"><i className="pulse-dot"/> 포트폴리오 평가 중</div><div className="top-actions"><Link href="/" className="secondary-button">추천 종목</Link></div></header><div className="content">
    <section className="detail-header"><div><p className="eyebrow">MY PORTFOLIO</p><h1 style={{margin:0,fontSize:30}}>보유 자산과 위험을 한눈에.</h1><p style={{color:"#819099",fontSize:11}}>평균단가를 입력하면 현재가·환율 기준으로 수익률과 종목 편중을 계산합니다.</p></div></section>
    <div className="portfolio-summary"><article className="summary-card"><span>총 평가금액</span><strong>{Math.round(totals.value).toLocaleString("ko-KR")}원</strong></article><article className="summary-card"><span>평가손익</span><strong className={pnl>=0?"positive":"negative"}>{pnl>=0?"+":""}{Math.round(pnl).toLocaleString("ko-KR")}원</strong></article><article className="summary-card"><span>수익률</span><strong className={pnl>=0?"positive":"negative"}>{(pnl/totals.cost*100).toFixed(2)}%</strong></article><article className="summary-card"><span>USD/KRW</span><strong>{fx.toLocaleString("ko-KR")}</strong></article></div>
    <section className="panel"><div className="panel-title"><div><span className="eyebrow">POSITIONS</span><h3>보유종목</h3></div><span className="updated">{positions.length}개</span></div><form className="position-form" onSubmit={addPosition}><select name="symbol" required defaultValue=""><option value="" disabled>종목 선택</option>{stocks.map((stock)=><option key={stock.symbol} value={stock.symbol}>{stock.name} ({stock.symbol})</option>)}</select><input name="qty" type="number" min="0.0001" step="any" placeholder="수량" required/><input name="avg" type="number" min="0" step="any" placeholder="평균단가" required/><input value="현재가 자동" disabled aria-label="현재가 자동 적용"/><button className="primary-button" type="submit">종목 추가</button></form>
    <div className="position-table"><div className="position-row header"><span>종목</span><span className="position-cell-right">수량</span><span className="position-cell-right">평균단가</span><span className="position-cell-right">현재가</span><span className="position-cell-right">평가금액</span><span className="position-cell-right">수익률</span><span/></div>{positions.map((p)=>{const rate=p.currency==="USD"?fx:1;const rr=(p.price/p.avg-1)*100;return <div className="position-row" key={p.symbol}><Link href={`/stock/${p.symbol}`} className="stock-identity"><span className="mini-logo">{p.name.slice(0,1)}</span><div><strong>{p.name}</strong><small>{p.symbol}</small></div></Link><span className="position-cell-right">{p.qty}</span><span className="position-cell-right">{p.currency==="USD"?"$":"₩"}{p.avg.toLocaleString()}</span><span className="position-cell-right">{p.currency==="USD"?"$":"₩"}{p.price.toLocaleString()}</span><strong className="position-cell-right">₩{Math.round(p.qty*p.price*rate).toLocaleString()}</strong><strong className={`position-cell-right ${rr>=0?"positive":"negative"}`}>{rr>=0?"+":""}{rr.toFixed(2)}%</strong><button className="delete-position" onClick={()=>setPositions((items)=>items.filter((item)=>item.symbol!==p.symbol))} aria-label={`${p.name} 삭제`}>×</button></div>})}</div></section><p className="disclaimer">브로커리지 계좌 자동 연동 전 단계의 로컬 포트폴리오 예시입니다. 환율은 최신 저장 스냅샷을 사용합니다.</p>
  </div></main></div>;
}
