"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Navigation } from "../../components/Navigation";
import { formatPrice, macro, news, type Stock } from "../../data";

const ranges = ["1일", "1주", "1개월", "3개월", "1년"];

export function StockDetail({ stock }: { stock: Stock }) {
  const [range, setRange] = useState("3개월");
  const [saved, setSaved] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [version, setVersion] = useState(1);
  const candles = useMemo(() => Array.from({ length: 42 }, (_, i) => ({ height: 26 + ((i * 29 + stock.symbol.length * 7) % 68), up: ((i * 17 + stock.symbol.charCodeAt(0)) % 5) !== 0 })), [stock]);
  function refresh() { setRefreshing(true); window.setTimeout(() => { setRefreshing(false); setVersion((value) => value + 1); }, 1100); }

  return <div className="app-shell"><Navigation /><main className="main-area">
    <header className="topbar"><div className="mobile-brand"><span className="brand-mark">S</span><strong>signalist</strong></div><div className="live-pill"><i className="pulse-dot" /> 시장 데이터 연결됨</div><div className="top-actions"><Link href="/" className="secondary-button">추천 목록</Link></div></header>
    <div className="content"><Link href="/" className="back-link">← 오늘의 시그널</Link>
      <section className="detail-header"><div className="security-heading"><span className="stock-logo logo-0">{stock.name.slice(0,1)}</span><div><h1>{stock.name}</h1><p>{stock.exchange} · {stock.symbol} · {stock.sector}</p></div></div><div className="quote-block"><strong>{formatPrice(stock)}</strong><span className={stock.change >= 0 ? "up" : "down"}>{stock.change >= 0 ? "+" : ""}{stock.change.toFixed(2)}% 오늘</span><div className="detail-actions"><button className={saved ? "secondary-button positive" : "secondary-button"} onClick={() => setSaved(!saved)}>{saved ? "★ 관심종목" : "☆ 저장"}</button><button className="primary-button" onClick={refresh} disabled={refreshing}>{refreshing ? "근거 갱신 중…" : "AI 재분석"}</button></div></div></section>
      <div className="detail-layout">
        <section className="detail-card"><div className="chart-toolbar"><h2>가격 추이</h2><div className="range-buttons">{ranges.map((item) => <button key={item} className={range === item ? "active" : ""} onClick={() => setRange(item)}>{item}</button>)}</div></div><div className="candle-chart" aria-label={`${stock.name} ${range} 캔들 차트`}>{candles.map((bar,i) => <i key={i} className={bar.up ? "candle" : "candle down-candle"} style={{"--h":`${bar.height}%`} as React.CSSProperties} />)}</div><div className="chart-caption"><span>거래량 조정 가격 · 데모 피드</span><span>고가 {formatPrice(stock,stock.price*1.028)} · 저가 {formatPrice(stock,stock.price*.973)}</span></div><div className="metric-grid"><div className="metric-box"><span>PER</span><strong>{stock.per.toFixed(1)}배</strong></div><div className="metric-box"><span>PBR</span><strong>{stock.pbr.toFixed(2)}배</strong></div><div className="metric-box"><span>ROE</span><strong>{stock.roe.toFixed(1)}%</strong></div></div></section>
        <aside className="detail-card"><div className="panel-title"><div><span className="eyebrow">FACTOR SCORE</span><h3>추천 점수 구성</h3></div><strong className="positive">{stock.score}/100</strong></div>{stock.factors.map((factor) => <div className="factor-row" key={factor.label}><div className="factor-label"><span>{factor.label}</span><b>{factor.value}</b></div><div className="factor-track"><i style={{width:`${factor.value}%`}} /></div></div>)}<div className="panel-title" style={{marginTop:28}}><h3>거시 민감도</h3><span className="updated">실시간 스냅샷</span></div>{macro.slice(0,3).map((item) => <div className="mini-stock" key={item.label}><div><strong>{item.label}</strong><small>{item.note}</small></div><b>{item.value}</b><em className={item.tone}>{item.change}</em></div>)}</aside>
        <section className={refreshing ? "detail-card analysis-card loading-shimmer" : "detail-card analysis-card"}><div className="analysis-head"><div className="analysis-title"><span className="ai-orbit">AI</span><div><span className="eyebrow">SENIOR ANALYST REPORT · V{version}</span><h2>{stock.action}: 실적의 방향과 가격 안전마진을 함께 확인</h2><p>재무·가격·공시·뉴스·거시 스냅샷 기준 · 방금 전 갱신</p></div></div><div className="confidence"><strong>{stock.confidence}%</strong><span>분석 신뢰도</span></div></div><div className="price-plan"><div className="plan-box"><span>현재가</span><strong>{formatPrice(stock)}</strong></div><div className="plan-box"><span>분할 매수 구간</span><strong className="positive">{formatPrice(stock,stock.price*.97)}–{formatPrice(stock,stock.price*.99)}</strong></div><div className="plan-box"><span>12개월 목표가</span><strong>{formatPrice(stock,stock.target)}</strong></div><div className="plan-box"><span>리스크 컷</span><strong className="negative">{formatPrice(stock,stock.stop)}</strong></div></div><div className="analysis-columns"><div><h4>핵심 투자 논리</h4><p>{stock.thesis} 성장률과 수익성을 함께 반영하면 현재 가격은 기대수익 대비 위험이 관리 가능한 구간입니다. 변동성을 이용한 분할 접근이 적절합니다.</p></div><div><h4>확인할 촉매</h4><ul><li>다음 분기 이익 추정치 상향</li><li>기관·외국인 수급 지속</li><li>업종 선행지표 개선</li></ul></div><div><h4>무효화 조건</h4><ul><li>{stock.risk}</li><li>목표 이익률 하향 전환</li><li>손절가 종가 이탈</li></ul></div></div></section>
        <section className="detail-card"><div className="panel-title"><div><span className="eyebrow">VALUATION</span><h3>밸류에이션 판독</h3></div><span className="action-badge buy">적정</span></div><p style={{color:"#89969c",fontSize:10,lineHeight:1.7}}>PER·PBR만 단독으로 보지 않고 ROE, 이익 성장률, 업종 중앙값과 금리 수준을 함께 비교합니다. 금리 상승 시 고멀티플 기업의 목표 배수는 자동으로 낮아집니다.</p><div className="metric-grid"><div className="metric-box"><span>PER 업종 대비</span><strong>-8.4%</strong></div><div className="metric-box"><span>PBR/ROE</span><strong>{(stock.pbr/stock.roe).toFixed(2)}</strong></div><div className="metric-box"><span>안전마진</span><strong className="positive">{((stock.target/stock.price-1)*100).toFixed(1)}%</strong></div></div></section>
        <section className="detail-card"><div className="panel-title"><div><span className="eyebrow">EVIDENCE FEED</span><h3>분석에 사용한 뉴스</h3></div><span className="updated">중복 제거됨</span></div>{news.map((item) => <article className="news-item" key={item.title}><strong>{item.title}</strong><span>{item.source} · {item.time} · 영향도 {item.materiality} · <b className={item.sentiment === "긍정" ? "positive" : "neutral"}>{item.sentiment}</b></span></article>)}</section>
      </div><p className="disclaimer">본 분석은 투자 참고용이며 매매 권유가 아닙니다. 목표가와 손절가는 데이터 기준 시점 이후 시장 상황에 따라 달라질 수 있습니다.</p>
    </div></main></div>;
}
