"""
종목 사전 데이터. `app/lib/symbol-dictionary.ts` 에서 **기계 생성**했다.

120개 항목을 손으로 옮기면 오타가 조용히 오탐·미탐을 만들므로 원본을 그대로
덤프했다. TS 를 삭제한 뒤에는 이 파일이 정본이 된다.

그룹명(삼성, 현대, LG)처럼 여러 상장사를 가리키는 말은 오탐이 많아 별칭에 넣지 않는다.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class SymbolEntry:
    symbol: str
    name: str
    market: str
    sector: str
    aliases: tuple[str, ...]


# 공유 버튼·앱 안내 문구. 종목명과 겹치므로 스캔 전에 제거한다(카카오톡 → 카카오 오탐).
NOISE_TERMS: tuple[str, ...] = (
    '카카오톡',
    '카카오스토리',
    '카카오채널',
    '네이버 블로그',
    '네이버블로그',
    '네이버 밴드',
    '네이버밴드',
    '네이버 뉴스',
    '네이버 메인',
    '구글 플레이',
    '애플 앱스토어',
    '구글플레이',
)

SYMBOL_DICTIONARY: tuple[SymbolEntry, ...] = (
    SymbolEntry('005930', '삼성전자', 'KR', '반도체', ('삼성전자', '삼성전자우')),
    SymbolEntry('000660', 'SK하이닉스', 'KR', '반도체', ('SK하이닉스', '하이닉스')),
    SymbolEntry('373220', 'LG에너지솔루션', 'KR', '2차전지', ('LG에너지솔루션', '엘지에너지솔루션', 'LG엔솔')),
    SymbolEntry('207940', '삼성바이오로직스', 'KR', '바이오', ('삼성바이오로직스', '삼바')),
    SymbolEntry('005380', '현대차', 'KR', '자동차', ('현대차', '현대자동차')),
    SymbolEntry('000270', '기아', 'KR', '자동차', ('기아자동차', '기아차')),
    SymbolEntry('005490', 'POSCO홀딩스', 'KR', '철강', ('POSCO홀딩스', '포스코홀딩스', '포스코')),
    SymbolEntry('051910', 'LG화학', 'KR', '화학', ('LG화학', '엘지화학')),
    SymbolEntry('006400', '삼성SDI', 'KR', '2차전지', ('삼성SDI',)),
    SymbolEntry('035420', 'NAVER', 'KR', '인터넷', ('네이버', 'NAVER')),
    SymbolEntry('035720', '카카오', 'KR', '인터넷', ('카카오',)),
    SymbolEntry('323410', '카카오뱅크', 'KR', '은행', ('카카오뱅크',)),
    SymbolEntry('377300', '카카오페이', 'KR', '핀테크', ('카카오페이',)),
    SymbolEntry('105560', 'KB금융', 'KR', '은행', ('KB금융', '국민은행', 'KB국민은행')),
    SymbolEntry('055550', '신한지주', 'KR', '은행', ('신한지주', '신한금융', '신한은행')),
    SymbolEntry('086790', '하나금융지주', 'KR', '은행', ('하나금융지주', '하나금융', '하나은행')),
    SymbolEntry('316140', '우리금융지주', 'KR', '은행', ('우리금융지주', '우리금융', '우리은행')),
    SymbolEntry('138040', '메리츠금융지주', 'KR', '증권', ('메리츠금융지주', '메리츠금융')),
    SymbolEntry('012450', '한화에어로스페이스', 'KR', '방산', ('한화에어로스페이스', '한화에어로')),
    SymbolEntry('047810', '한국항공우주', 'KR', '방산', ('한국항공우주', 'KAI')),
    SymbolEntry('064350', '현대로템', 'KR', '방산', ('현대로템',)),
    SymbolEntry('042660', '한화오션', 'KR', '조선', ('한화오션', '대우조선해양')),
    SymbolEntry('329180', 'HD현대중공업', 'KR', '조선', ('HD현대중공업', '현대중공업')),
    SymbolEntry('010140', '삼성중공업', 'KR', '조선', ('삼성중공업',)),
    SymbolEntry('009540', 'HD한국조선해양', 'KR', '조선', ('HD한국조선해양', '한국조선해양')),
    SymbolEntry('015760', '한국전력', 'KR', '유틸리티', ('한국전력', '한전')),
    SymbolEntry('034020', '두산에너빌리티', 'KR', '발전설비', ('두산에너빌리티', '두산중공업')),
    SymbolEntry('241560', '두산밥캣', 'KR', '기계', ('두산밥캣',)),
    SymbolEntry('000880', '한화', 'KR', '지주', ('한화솔루션', '한화시스템')),
    SymbolEntry('010130', '고려아연', 'KR', '비철금속', ('고려아연',)),
    SymbolEntry('011200', 'HMM', 'KR', '해운', ('HMM',)),
    SymbolEntry('003490', '대한항공', 'KR', '항공', ('대한항공',)),
    SymbolEntry('032640', 'LG유플러스', 'KR', '통신', ('LG유플러스', '엘지유플러스')),
    SymbolEntry('017670', 'SK텔레콤', 'KR', '통신', ('SK텔레콤', 'SKT')),
    SymbolEntry('030200', 'KT', 'KR', '통신', ('KT주식회사',)),
    SymbolEntry('066570', 'LG전자', 'KR', '가전', ('LG전자', '엘지전자')),
    SymbolEntry('009150', '삼성전기', 'KR', '전자부품', ('삼성전기',)),
    SymbolEntry('011070', 'LG이노텍', 'KR', '전자부품', ('LG이노텍',)),
    SymbolEntry('034730', 'SK', 'KR', '지주', ('SK이노베이션', 'SK온')),
    SymbolEntry('096770', 'SK이노베이션', 'KR', '정유', ('SK이노베이션',)),
    SymbolEntry('010950', 'S-Oil', 'KR', '정유', ('에쓰오일', 'S-Oil', '에스오일')),
    SymbolEntry('051900', 'LG생활건강', 'KR', '소비재', ('LG생활건강',)),
    SymbolEntry('090430', '아모레퍼시픽', 'KR', '화장품', ('아모레퍼시픽', '아모레')),
    SymbolEntry('097950', 'CJ제일제당', 'KR', '음식료', ('CJ제일제당',)),
    SymbolEntry('271560', '오리온', 'KR', '음식료', ('오리온',)),
    SymbolEntry('282330', 'BGF리테일', 'KR', '유통', ('BGF리테일', 'CU편의점')),
    SymbolEntry('069960', '현대백화점', 'KR', '유통', ('현대백화점',)),
    SymbolEntry('004170', '신세계', 'KR', '유통', ('신세계백화점',)),
    SymbolEntry('139480', '이마트', 'KR', '유통', ('이마트',)),
    SymbolEntry('068270', '셀트리온', 'KR', '바이오', ('셀트리온',)),
    SymbolEntry('128940', '한미약품', 'KR', '제약', ('한미약품',)),
    SymbolEntry('000100', '유한양행', 'KR', '제약', ('유한양행',)),
    SymbolEntry('326030', 'SK바이오팜', 'KR', '바이오', ('SK바이오팜',)),
    SymbolEntry('196170', '알테오젠', 'KR', '바이오', ('알테오젠',)),
    SymbolEntry('247540', '에코프로비엠', 'KR', '2차전지', ('에코프로비엠',)),
    SymbolEntry('086520', '에코프로', 'KR', '2차전지', ('에코프로',)),
    SymbolEntry('066970', '엘앤에프', 'KR', '2차전지', ('엘앤에프',)),
    SymbolEntry('003670', '포스코퓨처엠', 'KR', '2차전지', ('포스코퓨처엠',)),
    SymbolEntry('042700', '한미반도체', 'KR', '반도체장비', ('한미반도체',)),
    SymbolEntry('000990', 'DB하이텍', 'KR', '반도체', ('DB하이텍',)),
    SymbolEntry('403870', 'HPSP', 'KR', '반도체장비', ('HPSP',)),
    SymbolEntry('058470', '리노공업', 'KR', '반도체장비', ('리노공업',)),
    SymbolEntry('112040', '위메이드', 'KR', '게임', ('위메이드',)),
    SymbolEntry('036570', '엔씨소프트', 'KR', '게임', ('엔씨소프트', 'NC소프트')),
    SymbolEntry('251270', '넷마블', 'KR', '게임', ('넷마블',)),
    SymbolEntry('259960', '크래프톤', 'KR', '게임', ('크래프톤',)),
    SymbolEntry('352820', '하이브', 'KR', '엔터', ('하이브', 'HYBE')),
    SymbolEntry('041510', '에스엠', 'KR', '엔터', ('에스엠엔터테인먼트', 'SM엔터테인먼트')),
    SymbolEntry('122870', '와이지엔터테인먼트', 'KR', '엔터', ('와이지엔터테인먼트', 'YG엔터테인먼트')),
    SymbolEntry('035900', 'JYP Ent.', 'KR', '엔터', ('JYP엔터테인먼트',)),
    SymbolEntry('018260', '삼성에스디에스', 'KR', 'IT서비스', ('삼성에스디에스', '삼성SDS')),
    SymbolEntry('267250', 'HD현대', 'KR', '지주', ('HD현대',)),
    SymbolEntry('012330', '현대모비스', 'KR', '자동차부품', ('현대모비스',)),
    SymbolEntry('161390', '한국타이어앤테크놀로지', 'KR', '자동차부품', ('한국타이어',)),
    SymbolEntry('028260', '삼성물산', 'KR', '건설', ('삼성물산',)),
    SymbolEntry('000720', '현대건설', 'KR', '건설', ('현대건설',)),
    SymbolEntry('006360', 'GS건설', 'KR', '건설', ('GS건설',)),
    SymbolEntry('047050', '포스코인터내셔널', 'KR', '상사', ('포스코인터내셔널',)),
    SymbolEntry('078930', 'GS', 'KR', '지주', ('GS칼텍스',)),
    SymbolEntry('016360', '삼성증권', 'KR', '증권', ('삼성증권',)),
    SymbolEntry('005940', 'NH투자증권', 'KR', '증권', ('NH투자증권',)),
    SymbolEntry('006800', '미래에셋증권', 'KR', '증권', ('미래에셋증권',)),
    SymbolEntry('071050', '한국금융지주', 'KR', '증권', ('한국금융지주', '한국투자증권')),
    SymbolEntry('032830', '삼성생명', 'KR', '보험', ('삼성생명',)),
    SymbolEntry('000810', '삼성화재', 'KR', '보험', ('삼성화재',)),
    SymbolEntry('079550', 'LIG넥스원', 'KR', '방산', ('LIG넥스원',)),
    SymbolEntry('272210', '한화시스템', 'KR', '방산', ('한화시스템',)),
    SymbolEntry('298040', '효성중공업', 'KR', '전력기기', ('효성중공업',)),
    SymbolEntry('010120', 'LS ELECTRIC', 'KR', '전력기기', ('LS일렉트릭', 'LS ELECTRIC')),
    SymbolEntry('267260', 'HD현대일렉트릭', 'KR', '전력기기', ('HD현대일렉트릭', '현대일렉트릭')),
    SymbolEntry('NVDA', 'NVIDIA', 'US', '반도체', ('엔비디아', 'NVIDIA', 'NVDA')),
    SymbolEntry('AAPL', 'Apple', 'US', 'IT하드웨어', ('애플', 'Apple', 'AAPL')),
    SymbolEntry('MSFT', 'Microsoft', 'US', '소프트웨어', ('마이크로소프트', 'Microsoft', 'MSFT')),
    SymbolEntry('GOOGL', 'Alphabet', 'US', '인터넷', ('알파벳', '구글', 'Alphabet', 'GOOGL')),
    SymbolEntry('AMZN', 'Amazon', 'US', '유통', ('아마존', 'Amazon', 'AMZN')),
    SymbolEntry('META', 'Meta Platforms', 'US', '인터넷', ('메타플랫폼스', 'Meta Platforms', 'META')),
    SymbolEntry('TSLA', 'Tesla', 'US', '자동차', ('테슬라', 'Tesla', 'TSLA')),
    SymbolEntry('AVGO', 'Broadcom', 'US', '반도체', ('브로드컴', 'Broadcom', 'AVGO')),
    SymbolEntry('AMD', 'AMD', 'US', '반도체', ('AMD',)),
    SymbolEntry('INTC', 'Intel', 'US', '반도체', ('인텔', 'Intel', 'INTC')),
    SymbolEntry('MU', 'Micron', 'US', '반도체', ('마이크론', 'Micron')),
    SymbolEntry('TSM', 'TSMC', 'US', '반도체', ('TSMC', '타이완반도체')),
    SymbolEntry('ASML', 'ASML', 'US', '반도체장비', ('ASML',)),
    SymbolEntry('QCOM', 'Qualcomm', 'US', '반도체', ('퀄컴', 'Qualcomm', 'QCOM')),
    SymbolEntry('ARM', 'Arm Holdings', 'US', '반도체', ('Arm Holdings', 'ARM홀딩스')),
    SymbolEntry('JPM', 'JPMorgan Chase', 'US', '은행', ('JP모건', 'JPMorgan', 'JPM')),
    SymbolEntry('GS', 'Goldman Sachs', 'US', '증권', ('골드만삭스', 'Goldman Sachs')),
    SymbolEntry('BRK.B', 'Berkshire Hathaway', 'US', '복합', ('버크셔해서웨이', 'Berkshire')),
    SymbolEntry('LLY', 'Eli Lilly', 'US', '제약', ('일라이릴리', 'Eli Lilly')),
    SymbolEntry('NVO', 'Novo Nordisk', 'US', '제약', ('노보노디스크', 'Novo Nordisk')),
    SymbolEntry('JNJ', 'Johnson & Johnson', 'US', '제약', ('존슨앤드존슨', 'Johnson & Johnson')),
    SymbolEntry('XOM', 'Exxon Mobil', 'US', '에너지', ('엑슨모빌', 'Exxon')),
    SymbolEntry('BA', 'Boeing', 'US', '항공우주', ('보잉', 'Boeing')),
    SymbolEntry('NFLX', 'Netflix', 'US', '미디어', ('넷플릭스', 'Netflix', 'NFLX')),
    SymbolEntry('ORCL', 'Oracle', 'US', '소프트웨어', ('오라클', 'Oracle', 'ORCL')),
    SymbolEntry('PLTR', 'Palantir', 'US', '소프트웨어', ('팔란티어', 'Palantir', 'PLTR')),
    SymbolEntry('COIN', 'Coinbase', 'US', '핀테크', ('코인베이스', 'Coinbase')),
    SymbolEntry('UBER', 'Uber', 'US', '플랫폼', ('우버', 'Uber')),
    SymbolEntry('DIS', 'Walt Disney', 'US', '미디어', ('디즈니', 'Disney')),
    SymbolEntry('WMT', 'Walmart', 'US', '유통', ('월마트', 'Walmart')),
)
