# Generated by Django 5.2.17 on 2026-08-27 16:51

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LlmProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('base_url', models.TextField()),
                ('model', models.TextField()),
                ('api_key', models.TextField(default='')),
                ('priority', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('daily_limit', models.IntegerField(default=0)),
                ('used_today', models.IntegerField(default=0)),
                ('usage_date_kst', models.DateField(blank=True, null=True)),
                ('cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.TextField(default='대기')),
                ('last_error', models.TextField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'AI 공급자',
                'verbose_name_plural': 'AI 공급자',
                'db_table': 'llm_providers',
                'ordering': ['is_active', 'priority'],
                'indexes': [models.Index(fields=['is_active', 'priority'], name='llm_prov_order_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('url', models.TextField(unique=True)),
                ('resolved_url', models.TextField(blank=True, null=True)),
                ('symbol', models.TextField()),
                ('company', models.TextField()),
                ('category', models.TextField(default='종합')),
                ('crawl_hour_kst', models.IntegerField(default=6)),
                ('max_pages', models.IntegerField(default=1)),
                ('window_hours', models.IntegerField(default=36)),
                ('is_active', models.BooleanField(default=True)),
                ('etag', models.TextField(blank=True, null=True)),
                ('last_modified', models.TextField(blank=True, null=True)),
                ('last_status', models.TextField(default='대기')),
                ('last_error', models.TextField(blank=True, null=True)),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
                ('next_crawl_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': '뉴스 소스',
                'verbose_name_plural': '뉴스 소스',
                'db_table': 'news_sources',
                'ordering': ['-is_active', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'next_crawl_at'], name='news_src_due_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.TextField()),
                ('title', models.TextField()),
                ('canonical_url', models.TextField(unique=True)),
                ('excerpt', models.TextField(default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.TextField()),
                ('sentiment', models.TextField()),
                ('sentiment_score', models.IntegerField()),
                ('materiality', models.TextField()),
                ('relevance', models.IntegerField()),
                ('event_type', models.TextField()),
                ('score_adjustment', models.IntegerField()),
                ('analysis_summary', models.TextField()),
                ('collected_at', models.DateTimeField()),
                ('published_date_kst', models.GeneratedField(db_persist=True, expression=django.db.models.functions.comparison.Cast(models.Func(django.db.models.functions.comparison.Coalesce('published_at', 'collected_at'), models.Value('Asia/Seoul'), arg_joiner=' AT TIME ZONE ', function='timezone', template='(%(expressions)s)'), output_field=models.DateField()), output_field=models.DateField())),
                ('insight_status', models.TextField(choices=[('대기', '대기'), ('완료', '완료'), ('제외', '제외'), ('오류', '오류')], default='대기')),
                ('source', models.ForeignKey(db_column='source_id', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.newssource')),
            ],
            options={
                'verbose_name': '수집 기사',
                'verbose_name_plural': '수집 기사',
                'db_table': 'news_articles',
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticleSymbol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.TextField()),
                ('company', models.TextField()),
                ('market', models.TextField(default='KR')),
                ('sector', models.TextField(default='')),
                ('match_type', models.TextField(default='사전')),
                ('mentions', models.IntegerField(default=1)),
                ('relevance', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField()),
                ('article', models.ForeignKey(db_column='article_id', on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='news.newsarticle')),
            ],
            options={
                'verbose_name': '기사 종목',
                'verbose_name_plural': '기사 종목',
                'db_table': 'news_article_symbols',
                'ordering': ['-relevance'],
                'indexes': [models.Index(fields=['symbol', 'created_at'], name='news_sym_symbol_idx')],
                'constraints': [models.UniqueConstraint(fields=('article', 'symbol'), name='news_sym_article_symbol_uq')],
            },
        ),
        migrations.CreateModel(
            name='NewsInsight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('summary', models.TextField(default='')),
                ('keywords', models.JSONField(default=list)),
                ('sectors', models.JSONField(default=list)),
                ('evidence', models.JSONField(default=list)),
                ('sentiment', models.TextField(default='중립')),
                ('sentiment_score', models.IntegerField(default=50)),
                ('materiality', models.TextField(default='낮음')),
                ('event_type', models.TextField(default='산업·시장동향')),
                ('impact_horizon', models.TextField(default='당일')),
                ('market_view', models.TextField(default='')),
                ('body_chars', models.IntegerField(default=0)),
                ('engine', models.TextField(default='규칙 기반')),
                ('model', models.TextField(default='')),
                ('attempts', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('article', models.OneToOneField(db_column='article_id', on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='news.newsarticle')),
            ],
            options={
                'verbose_name': '본문 분석',
                'verbose_name_plural': '본문 분석',
                'db_table': 'news_insights',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['keywords'], name='news_insights_keywords_gin'), django.contrib.postgres.indexes.GinIndex(fields=['sectors'], name='news_insights_sectors_gin')],
            },
        ),
        migrations.CreateModel(
            name='NewsCrawlRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.TextField(choices=[('실행 중', '실행 중'), ('완료', '완료'), ('변경 없음', '변경 없음'), ('새 기사 없음', '새 기사 없음'), ('오류', '오류')])),
                ('fetched_count', models.IntegerField(default=0)),
                ('inserted_count', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(db_column='source_id', on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='news.newssource')),
            ],
            options={
                'verbose_name': '수집 실행',
                'verbose_name_plural': '수집 실행',
                'db_table': 'news_crawl_runs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source', 'started_at'], name='news_run_src_started_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['published_date_kst', 'published_at'], name='news_art_pubdate_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['source', 'collected_at'], name='news_art_src_coll_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['insight_status', 'published_at'], name='news_art_queue_idx'),
        ),
    ]
