# Generated by hand — drizzle 가 만든 인덱스 이름을 Django 규약으로 맞춘다.
#
# 이식 중에는 스키마 소유자가 drizzle 이었고, 그 인덱스 이름이 Django 의 30자 제한을
# 넘거나 규약과 달랐다. 0001 은 `--fake-initial` 로 적용했으므로 DDL 이 실행되지 않아
# 기존 이름이 그대로 남아 있다. 이름이 어긋나면 앞으로의 마이그레이션이 없는 인덱스를
# 지우려 하거나 있는 것을 또 만들려 한다.
#
# 개명은 즉시 끝나고 락도 짧다. 빈 DB 에서는 이미 Django 이름으로 만들어지므로
# `IF EXISTS` 로 무시된다.

from django.db import migrations

RENAMES = [
    ("news_sources_url_unique", "news_sources_url_key"),
    ("news_sources_due_idx", "news_src_due_idx"),
    ("news_articles_canonical_url_unique", "news_articles_canonical_url_key"),
    ("news_articles_published_date_idx", "news_art_pubdate_idx"),
    ("news_articles_source_collected_idx", "news_art_src_coll_idx"),
    ("news_articles_insight_queue_idx", "news_art_queue_idx"),
    ("news_insights_article_unique", "news_insights_article_id_key"),
    ("news_article_symbols_unique", "news_sym_article_symbol_uq"),
    ("news_article_symbols_symbol_idx", "news_sym_symbol_idx"),
    ("news_crawl_runs_source_started_idx", "news_run_src_started_idx"),
    ("llm_providers_name_unique", "llm_providers_name_key"),
    ("llm_providers_order_idx", "llm_prov_order_idx"),
]


def _sql(pairs: list[tuple[str, str]]) -> str:
    return "".join(
        f'ALTER INDEX IF EXISTS "{old}" RENAME TO "{new}";' for old, new in pairs
    )


class Migration(migrations.Migration):
    dependencies = [("news", "0001_initial")]

    operations = [
        migrations.RunSQL(
            sql=_sql(RENAMES),
            reverse_sql=_sql([(new, old) for old, new in RENAMES]),
        ),
    ]
