# Generated by hand — Django 가 만드는데 drizzle 은 만들지 않던 인덱스를 채운다.
#
# 두 부류다.
#
# 1. **FK 인덱스** — Django 는 ForeignKey 마다 인덱스를 만든다. drizzle 은 만들지 않았다.
#    조인과 cascade 삭제가 이 인덱스를 쓴다.
# 2. **`text_pattern_ops`** — `unique=True` 인 text 컬럼에 Django 가 추가하는 것으로,
#    `LIKE 'prefix%'` 접두어 검색이 인덱스를 타게 한다. 기본 btree 는 C 로케일이 아니면
#    LIKE 에 쓰이지 않는다.
#
# 0001 을 `--fake-initial` 로 적용했기 때문에 이 DDL 이 실행되지 않았다. 빈 DB 에서는
# 이미 만들어져 있으므로 `IF NOT EXISTS` 로 무시된다.

from django.db import migrations

INDEXES = [
    ("news_sources_url_bfbe09e0_like", 'news_sources', 'url text_pattern_ops'),
    ("news_articles_canonical_url_9cf74bdd_like", 'news_articles', 'canonical_url text_pattern_ops'),
    ("news_articles_source_id_024fa0ae", 'news_articles', 'source_id'),
    ("news_article_symbols_article_id_e1941858", 'news_article_symbols', 'article_id'),
    ("news_crawl_runs_source_id_bb7a38dd", 'news_crawl_runs', 'source_id'),
    ("llm_providers_name_ab239e40_like", 'llm_providers', 'name text_pattern_ops'),
]


class Migration(migrations.Migration):
    dependencies = [("news", "0002_align_index_names")]

    operations = [
        migrations.RunSQL(
            sql="".join(
                f'CREATE INDEX IF NOT EXISTS "{name}" ON "{table}" ({cols});'
                for name, table, cols in INDEXES
            ),
            reverse_sql="".join(
                f'DROP INDEX IF EXISTS "{name}";' for name, _, _ in INDEXES
            ),
        ),
    ]
