# Generated by Django 5.2.17 on 2026-08-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_add_django_side_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='crawl_interval_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
